### ISSUE TITLE
版本更新

### ISSUE THREAD

**Issue by rucieryi369** [LeeSureman/Sequence-Labeling-Early-Exit#2]
看main.py的時候有些导入的包是找不到的，所以什么时候更新呢？

**Comment by LeeSureman** [comment]
你指的是requirements.py吗

**Comment by rucieryi369** [comment]
main.py中导入tmp_fastnlp_module和load_data_中导入的load_data在目录下没有找到

**Comment by LeeSureman** [comment]
ok，传了，

**Comment by rucieryi369** [comment]
感谢，load_data_.py中的load_data还没传

**Comment by rucieryi369** [comment]
感谢！很棒的工作

**Comment by rucieryi369** [comment]
load_data_.py中的yangjie_rich_pretrain_unigram_path,yangjie_rich_pretrain_bigram_path是怎么设置呢

**Comment by rucieryi369** [comment]
main.py中的from V0.modeling_bert_ee import BERT_SeqLabel_EE的modeling_bert_ee是modeling_bert_ee_old吗，futher_train.py中的SequentialSpanFMetric是在哪个包呢？多有打扰，谢谢！

**Comment by LeeSureman** [comment]
第一个问题，对的

**Comment by LeeSureman** [comment]
第二个问题的话，那个东西和这篇paper没关系，我刚更新了一下，没有了

**Comment by rucieryi369** [comment]
请问test.py指的是哪一个呢，谢谢

**Comment by LeeSureman** [comment]
之前忘记add了..现在加进来了

**Comment by rucieryi369** [comment]
谢谢，在test.py中的count_bert_self_att_called_by_bertlayer_ee是从cal_custom_flops导入的吗？现在cal_custom_flops没有找到，还有一个问题是fitlog.set_log_dir('logs_test_sentee')会出现NotADirectoryError: `logs_test_sentee` is not exist.

**Comment by LeeSureman** [comment]
刚传上来了, logs_test_sentee这个可能得自己新建一下,或者你加上os.makedirs(...,exitst_ok=True)
