### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by rucieryi369** [LeeSureman/Sequence-Labeling-Early-Exit#3]
请问用已训练好的模型，新的sentences输入的时候，怎么来进行预测呢

**Comment by LeeSureman** [comment]
这个你可能得参考一下fastNLP的predictor,类似:https://github.com/fastnlp/fastNLP/issues/262

**Comment by rucieryi369** [comment]
还有一个问题是预测数据怎么进行处理呢
